[toolchain]
channel = "stable"
targets = [
    # MacOS
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",

    # Linux
    "x86_64-unknown-linux-gnu",
    "i686-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",

    # iOS
    "aarch64-apple-ios",
    "x86_64-apple-ios",
    "aarch64-apple-ios-sim",
]
components = ["clippy", "rustfmt"]