[group("Repo")]
[doc("Default command; list all available commands.")]
@list:
  just --list --unsorted

[group("Repo")]
[doc("Open repo on GitHub in your default browser.")]
repo:
  open https://github.com/bitcoindevkit/rust-cktap

[group("Repo")]
[doc("Build the API docs.")]
docs:
  ./gradlew :lib:dokkaGeneratePublicationHtml

[group("Build")]
[doc("Build the library for given ARCH.")]
build ARCH="macos-aarch64":
  bash ./scripts/release/build-release-{{ARCH}}.sh

[group("Build")]
[doc("Build the library for a single architecture in development mode.")]
build-dev:
  bash ./scripts/dev/build-dev-macos-aarch64.sh

[group("Build")]
[doc("List available architectures for the build command.")]
@list-architectures:
    echo "Available architectures:"
    echo "    - macos-aarch64"

[group("Build")]
[doc("Remove all caches and previous build directories to start from scratch.")]
clean:
  rm -rf ../target/
  rm -rf ./build/
  rm -rf ./lib/build/
  rm -rf ./lib/src/main/kotlin/org/bitcoindevkit/cktap/*
  rm -rf ./lib/src/main/kotlin/com/coinkite/cktap/*
  rm -rf ./lib/src/main/jniLibs/*

[group("Publish")]
[doc("Publish the library to your local Maven repository (no signing, no credentials needed).")]
publish-local:
  ./gradlew publishToMavenLocal -P localBuild

[group("Publish")]
[doc("Publish the library to Maven Central (requires signing key and Sonatype credentials).")]
publish-central:
  ./gradlew publishAndReleaseToMavenCentral

[group("Test")]
[doc("Run all connected device tests.")]
test:
  ./gradlew connectedAndroidTest
