default:
    just --list

format:
    swift-format format -i Tests/CKTapTests/*.swift

build:
    bash ./build-xcframework.sh

clean:
    cargo clean
    rm -rf Sources
    rm -rf .build
    rm -rf *.xcframework

test: format
    swift test
